flex:
	jflex Tiger.flex
	javac Yylex.java
	java Yylex test.tig

# flex dump:
# 	jflex --dump Tiger.flex
# 	javac Yylex.java
# 	java Yylex test.tig

clear:
	rm -f *.class
	rm -f *.class~
	rm -f *.java
	rm -f *.java~
