
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexsyn;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int UMINUS = 8;
  public static final int LCBRACK = 3;
  public static final int NUMBER = 11;
  public static final int SEMI = 4;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int IF = 2;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int TIMES = 7;
  public static final int LPAREN = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "LCBRACK",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "NUMBER"
  };
}

